### ISSUE TITLE
example has loop={true} twice

### ISSUE THREAD

**Issue by lucidrains** [stelatech/react-anime#3]
![screen shot 2016-09-09 at 2 45 58 pm](https://cloud.githubusercontent.com/assets/108653/18403876/2f4ae582-769c-11e6-88f6-ca1abeaff433.png)

**Comment by kennetpostigo** [comment]
@lucidrains thanks for the heads up! Will tell @alaingalvan to replace his gif :)

**Comment by alaingalvan** [comment]
![Alrighty, Corrected!](https://github.com/stelatech/react-anime/raw/master/assets/cover.gif)

Corrected, thanks! ;)
