### ISSUE TITLE
Anime component makes div disappear

### ISSUE THREAD

**Issue by luandro** [stelatech/react-anime#5]
Am I doing something wrong?
```
import Anime from 'react-anime';

function Header() {
   return (
      <div>
         <h1>Header</h1>
         <Anime>
           <div style={{ width: 40, height: 40, background: 'blue' }} />
         </Anime>
      </div>
   )
}

```

I've tried adding the props from the example, but without them I also get the same result. It simply makes my `div` disappear.

**Comment by kennetpostigo** [comment]
@luandro can you make a codepen of this so that we can inspect and see whats going on? Heres a base template for a [codepen](http://codepen.io/alaingalvan/pen/EgjbKP?editors=0010)

**Comment by kennetpostigo** [comment]
@luandro actually I spotted the bug and it should be fixed. `npm install react-anime` to `v0.2.0`. It should be working. Thank you for raising this issue :)

**Comment by kennetpostigo** [comment]
@luandro if the problem went away with `v0.2.2` feel free to close the issue.

**Comment by luandro** [comment]
@kennetpostigo got fixed, thanks a lot and great job on the project!
