### ISSUE TITLE
composite components

### ISSUE THREAD

**Issue by queckezz** [stelatech/react-anime#6]
This currently does not work:

```js
class Button extends React.Component {
  render () {
    return <button>{this.props.children}</button>
  }
}

// functional components don't work anyway because we can't attach a ref
// const Button = ({ children }) => <button>{children}</button>

function App () {
  return (
    <Anime opacity={[0, 1]} translateY={'1em'}>
      <Button>Hello World</Button>
    </Anime>
  )
}
```

We could solve this by querying the raw dom node using `findDOMNode()` but that would make it even more incompatible with `react-native` because of the `react-dom` dep.

**Comment by kennetpostigo** [comment]
@queckezz thank you for bringing up this issue! @alaingalvan and I will look into this as soon as time allows.

**Comment by alaingalvan** [comment]
One workaround is to wrap the stateless component in a `<span>` or `<g>` element 
```js
<Anime ...>
  <g>
    <Egoraptor/>
  </g>
</Anime>
```

I'll be adding this to a set of commits I'm working on to improve control over animations based on the experience we got from a project @kennetpostigo is releasing this Sunday.  :3

**Comment by kennetpostigo** [comment]
Closing the issue now, this work around seems to work perfectly. @queckezz lmk if theres an edge case you run into.

**Comment by seleckis** [comment]
I think this should be reopened. `<g>` is not allowed as html-element, as well as `<span>` is inline-level element which sometimes can break layout. Yet another problem: Anime is not working with styled-components wrapper.
